name: Onnx Model Export

on:
  push:
  workflow_dispatch:

jobs:
  onnx_export:
    name: Onnx Export
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        model-name:
          - 'web'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up python dependences
        run: |
          pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-zoo.txt
      - name: Transform models to onnx format
        run: |
          python -m zoo.${{ matrix.model-name }} export -O . 
          ls -al .
          zip -r ${{ matrix.model-name }}.zip *.onnx
      - name: Upload the character databases
        uses: actions/upload-artifact@v3
        with:
          name: onnx-models
          path: ${{ matrix.model-name }}.zip

  data_upload:
    name: Data Upload
    runs-on: ${{ matrix.os }}
    needs:
      - onnx_export
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.8'

    steps:
      - name: Prepare the repository
        shell: bash
        run: |
          sudo apt-get install -y tree
          git lfs install
          git clone https://huggingface.co/OpenDILabCommunity/webpage_element_detection
          ls -al webpage_element_detection
      - name: Download from artifact
        uses: actions/download-artifact@v3
        with:
          name: onnx-models
          path: webpage_element_detection
      - name: See what is in this path
        shell: bash
        run: |
          cd webpage_element_detection
          for zfile in *.zip; do unzip -o $zfile; done
          rm -rf *.zip
          tree .
      - name: Push models to hugging face repostory
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd webpage_element_detection
          git config user.name 'hansbug'
          git config user.email 'hansbug@buaa.edu.cn'
          git add -A
          git diff-index --quiet HEAD || git commit -a -m "dev(hansbug): model publish $(date -R)"
          git push https://hansbug:$HF_TOKEN@huggingface.co/OpenDILabCommunity/webpage_element_detection main
